package topic10.quizFinal;public class NewException {    public static void main(String[ ] args) {                 int x, i = 0;                 int j = 10;                 try {                        System.out.println("Begin Calculation");                         x = j / i;                         System.out.println("After Calculation");                     } catch (ArithmeticException e) {                          System.out.println("Caught ArithmeticException");                     } catch (java.lang.Exception e) {                          System.out.println("Caught Exception");                     } finally {                          System.out.println("Finally Block");                     }                 System.out.println("End Program");             }}